"""Parses generated captions back into (class, position) tuples.

The model is trained on captions of the form:
    "A person at center. A car at bottom-left."

This module extracts the (class, position) pairs from such text. Generated
captions may not match the template perfectly — anything that doesn't parse is
silently skipped. That's fine: those become false negatives in the metric.
"""

import re

VALID_POSITIONS = frozenset({
    "top-left", "top", "top-right",
    "left", "center", "right",
    "bottom-left", "bottom", "bottom-right",
})

# Matches a single phrase: "A <class> at <position>" (period optional, case-insensitive).
# The class is captured non-greedily so multi-word classes ("fire hydrant") work.
_PHRASE_RE = re.compile(
    r"^\s*[Aa]n?\s+(.+?)\s+at\s+([a-z\-]+)\s*$",
    re.IGNORECASE,
)


def parse_caption(caption: str, valid_classes: frozenset) -> list[tuple[str, str]]:
    """Extract (class, position) pairs from a caption string.

    Args:
        caption: free-form text generated by the VLM.
        valid_classes: set of accepted class names (lowercased).

    Returns:
        List of (class, position) tuples. Phrases that don't match the template
        or reference unknown classes/positions are dropped.
    """
    results: list[tuple[str, str]] = []
    for phrase in caption.split("."):
        m = _PHRASE_RE.match(phrase)
        if m is None:
            continue
        class_name = m.group(1).strip().lower()
        position = m.group(2).strip().lower()
        if class_name in valid_classes and position in VALID_POSITIONS:
            results.append((class_name, position))
    return results
